### ISSUE TITLE
Range check error

### ISSUE THREAD

**Issue by ice-product96** [HemulGM/VK_API#3]
ошибка возникает в модуле vk.message
function TVkParamsMessageSend.RandomId(const Value: Integer): TVkParamsMessageSend;
begin
  if Value = -1 then
    List.Add('random_id', GetRandomId)
  else
    List.Add('random_id', Value);
  Result := Self;
end;
функция принимает integer но Params.RandomId(GetRandomId);    GetRandomId result = int64

**Comment by HemulGM** [comment]
Ошибка связана немного не с этим, но я вроде поправил. Буду ждать фидбека
